# Generated by Django 2.1.1 on 2018-09-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresas',
            options={'managed': False, 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='operadores',
            options={'managed': False, 'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.AlterModelOptions(
            name='personas',
            options={'managed': False, 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
