# Generated by Django 2.1.1 on 2018-09-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20180929_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operadores',
            options={'managed': False, 'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
    ]
