# Generated by Django 2.1.1 on 2018-09-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20180929_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operadores',
            options={'managed': False, 'permissions': {('view_oper', 'View Operadores')}, 'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
    ]
