# Generated by Django 2.1.1 on 2018-09-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20180929_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresas', models.IntegerField()),
                ('chapa', models.CharField(max_length=12, unique=True)),
                ('coche_numero', models.IntegerField()),
                ('observaciones', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'buses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprobantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('num_doc', models.CharField(max_length=20)),
                ('monto_a_pagar', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'comprobantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lectores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'lectores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lineas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'lineas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=16)),
                ('fecha_expedicion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.IntegerField()),
                ('saldo_actual', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
            options={
                'db_table': 'tarjetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timbrados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('valido_desde', models.DateField()),
                ('valido_hasta', models.DateField()),
                ('num_doc_ini', models.CharField(max_length=20)),
                ('num_doc_fin', models.CharField(max_length=20)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'timbrados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoBuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tipo_buses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_boleta', models.CharField(max_length=12)),
                ('descripcion', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tipo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trayectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramal', models.CharField(max_length=30)),
                ('itinerario_ida', models.CharField(max_length=500)),
                ('itinerario_vuelta', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'trayectos',
                'managed': False,
            },
        ),
    ]
