# Generated by Django 2.1.1 on 2018-09-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_buses_caja_comprobantes_lectores_lineas_movimientos_tarjetas_timbrados_tipobuses_tipopago_tipotarjet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buses',
            options={'managed': False, 'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='caja',
            options={'managed': False, 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterModelOptions(
            name='comprobantes',
            options={'managed': False, 'verbose_name': 'Comprobante', 'verbose_name_plural': 'Comprobantes'},
        ),
        migrations.AlterModelOptions(
            name='lectores',
            options={'managed': False, 'verbose_name': 'Lector', 'verbose_name_plural': 'Lectores'},
        ),
        migrations.AlterModelOptions(
            name='lineas',
            options={'managed': False, 'verbose_name': 'Linea', 'verbose_name_plural': 'Lineas'},
        ),
        migrations.AlterModelOptions(
            name='movimientos',
            options={'managed': False, 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='tarjetas',
            options={'managed': False, 'verbose_name': 'Tarjeta', 'verbose_name_plural': 'Tarjetas'},
        ),
        migrations.AlterModelOptions(
            name='timbrados',
            options={'managed': False, 'verbose_name': 'Timbrado', 'verbose_name_plural': 'Timbrados'},
        ),
        migrations.AlterModelOptions(
            name='tipobuses',
            options={'managed': False, 'verbose_name': 'Tipo Bus', 'verbose_name_plural': 'Tipo Buses'},
        ),
        migrations.AlterModelOptions(
            name='tipopago',
            options={'managed': False, 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='tipotarjeta',
            options={'managed': False, 'verbose_name': 'Tipo Tarjeta', 'verbose_name_plural': 'Tipo Tarjetas'},
        ),
        migrations.AlterModelOptions(
            name='trayectos',
            options={'managed': False, 'verbose_name': 'Trayecto', 'verbose_name_plural': 'Trayectos'},
        ),
        migrations.AlterModelTable(
            name='comprobantes',
            table='Comprobantes',
        ),
    ]
